project:
  type: book

book:
  title: "Computational Physics: Problem Solving with Julia"
  author: "Colton Quirk"
  date: "5/1/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/ch1/diffeq.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



